Messages v1 (#407)
* starting off messages

* bringing over paul's stuff, updating for other work that's been done to the api in the interim.

* fixing linter issues

* Messaging -> Messages

* Update messages.yml (#440)

* Update messages.yml

Added MMS vCard, WA custom to outbound, and reply, profile, context, provider-message to inbound

* incremented version number

Co-authored-by: Paul Ardeleanu <pardel@gmail.com>

* updated to latest version of the renderer

* removed required for Custom/properties/custom

Error:  650:11  error  required-object-params     #/components/schemas/Custom/allOf/1 is defined as a required object, but no child fields are required
Error:  650:11  error  required-property-example  #/components/schemas/Custom/allOf/1/properties/custom is defined as a required object and is missing an example

* Messages v1 (#446)

* Update messages.yml

Added MMS vCard, WA custom to outbound, and reply, profile, context, provider-message to inbound

* incremented version number

* Update messages.yml

Correct vCard example. Add additionalProperties to Customer. Add object definition to Reply

Co-authored-by: Paul Ardeleanu <pardel@gmail.com>

* renamed messages-olympus and added versions

* Small fixes to Messages v1 spec

* Removing required flag from custom type in Messages v1 spec

* corrected 422 & 429 descriptions

Co-authored-by: smackellar <33375526+smackellar@users.noreply.github.com>
Co-authored-by: Paul Ardeleanu <pardel@gmail.com>
Co-authored-by: Paul Ardeleanu <paul.ardeleanu@vonage.com>
Co-authored-by: superchilled <karl@superchilled.co.uk>